### ISSUE TITLE
Use Case: Hive page on Teach.mozilla.org

### ISSUE THREAD

**Issue by hannahkane** [mozilla/mofo-cms-experiment#13]
Background: We want to retire https://hivelearningnetworks.org soon, but first we need to create a page on the Teach site that preserves some, but not all, of the content.

The content of the new page will be:
- Updated copy about Hive, and its relationship with Mozilla (rarely updated)
- Links to Hive cities (individual websites and twitter) (requires regular, but not frequent, updating)
- "Planet Hive"—display blog posts from existing Hive city blogs

We do not have wireframes or mock-ups for this project. We could ask a designer to work within the constraints of Calypso.

This would give us an opportunity to prototype Calypso within an existing site (teach.m.o).

**Comment by mmmavis** [comment]
:exclamation: This ticket is now locked. Please continue the discussion on https://github.com/mozilla/wp-calypso instead. For more info see [README](https://github.com/mozilla/mofo-cms-experiment).
