### ISSUE TITLE
Use Case: Gigabit Site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/mofo-cms-experiment#14]
We currently maintain a small site at https://www.mozilla.org/en-US/gigabit/ describing the Gigabit Community Fund we manage. 

There are no content changes needed, but we want to do a redesign to bring the site into better brand alignment with our other properties.

The design refresh thinking has started here: https://redpen.io/p/vj24b1b75c486dac28. (But this should not be considered a final design.)

The site content needs to be updated a few times a year.

Note: this site is currently hosted on mozilla.org, but we could potentially change that.

**Comment by hannahkane** [comment]
@vazquez - this is another potential good use case for tiles. Want to take a look at the [redpen](https://redpen.io/p/vj24b1b75c486dac28) and see if the content could fit into the existing layouts, or if new layouts are needed?

**Comment by mmmavis** [comment]
:exclamation: This ticket is now locked. Please continue the discussion on https://github.com/mozilla/wp-calypso instead. For more info see [README](https://github.com/mozilla/mofo-cms-experiment).
