### ISSUE TITLE
Prototype Candidate: Mozilla Clubs Resources landing page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/mofo-cms-experiment#15]
We expect to have ~40 different resources for Club Captains (currently living in this [google doc](https://docs.google.com/document/d/1qLwEJZXF6Dz1wZ71AIC8t8n1LHPC6n99kZdFTuvB-LQ/edit)) that we need to make accessible to Club Captains and Regional Coordinators.

The list of resources is likely to need updating regularly, but not frequently.

No design yet; could be designed within Calypso design constraints.

We're working on having the individual resources localized, so it would be useful to think through a process for creating new landing pages on a per language basis. 

The landing page would likely live on teach.m.o, so it's an opportunity to use Calypso within an existing site.

**Comment by mmmavis** [comment]
Hey @hannahkane 

Are we talking about using Calypso to edit the landing page that contains a list of external links? Or those 40+ resource pages that are likely to be hosted on teach.m.o? I assume it's the latter, but thought I should double check with you.

**Comment by hannahkane** [comment]
This ticket was just about building the landing page, because Amira is comfortable building the resources themselves as github pages. 

But I'll likely file a separate ticket that's about creating a Calypso template for the resources themselves (adapting what Luke has already done with the design).

**Comment by mmmavis** [comment]
@hannahkane cool, thanks for the clarification!

**Comment by hannahkane** [comment]
Just realized I'd already created that ticket - it's #21. We might want to prioritize that even though it's a P2. Let's discuss soon.

**Comment by vazquez** [comment]
An idea for design with Foxlight:

![clubs guide](https://cloud.githubusercontent.com/assets/1119821/13088309/bd8c3b14-d4b9-11e5-88cf-0d472fb437e1.png)
- The first three boxes correspond to featured links (or important links)
- It would be a good idea to arrange these links alphabetically

**Comment by vazquez** [comment]
Or a 2-column layout

![2-column](https://cloud.githubusercontent.com/assets/1119821/13089417/79211c6a-d4be-11e5-82ce-b70e3fe1e009.png)

**Comment by mmmavis** [comment]
Will chat with @simonwex on how we should approach this during our 1:1 this afternoon.

Maybe we can use Pomax's [ReactRoutedExample](https://github.com/Pomax/ReactRoutedExample) (I see this as a boilerplate repo), hook it up with WordPress REST API, and apply Foxlight to it as the start point? :open_mouth:

**Comment by hannahkane** [comment]
Looks nice, @vazquez.

Wondering if the top level items need a title (same style as "Guides"). And are those pink rectangles placeholders for images, or is that the graphic we'd use? It looks to me like each of those rectangles is going to link to another landing page with more links on it, rather than directly to a resource.

@amirad - would like your thoughts on this, too, since you're the key stakeholder. I imagine you might want to group the documents into even more sub-categories (making use of that title style again, like the one used in "Guides")—it would help the user more quickly find what they're looking for.

**Comment by vazquez** [comment]
@hannahkane – You're right. I've shortened the size of the featured blocks so that they don't feel empty (or placeholder for images).

I still have to make this design match with Luke's templates.

![2-column](https://cloud.githubusercontent.com/assets/1119821/13114346/199fbc30-d561-11e5-9eac-a309aebf3afa.png)

**Comment by amirad** [comment]
Woah woah woah! Simple and perfect @vazquez 

Yes, I think we might need to have some subheaders for the guides so people don't have to shift through them all. Some can be 'teach like mozilla' 'marketing' 'mozilla club in your....." 
What about for different languages? I think it might be hard to find various languages buried among the other guides. Should we have a portugese/spanish/etc section?

My main concern is how easy is this going to be to update for our team? Can we easily go in and change and add links?

**Comment by hannahkane** [comment]
[side note: don't want to disrupt the work being done on this ticket, which addresses the specific use case of Clubs, but also opened up a more generic ticket for "List" layouts: see #25)]

**Comment by hannahkane** [comment]
Sounds like we need a second level of heading styles to accommodate lists with items in multiple categories. 

Would love some UX perspective (@flukeout, @kristinashu, @vazquez) on how to best handle localized versions of the linked content.

@amirad - making this easy for your team to update is our top priority! That's why we moved this ticket into the CMS repo, in fact. Our goal is to create a generic template for a page like this (we're using the Clubs Resources as one of the first use cases), and then you and your team will have access to a front-end editor (that will look pretty much exactly like editing a blog post or page on Wordpress) to make and push updates any time.

@mmmavis @gvn @simonwex—please correct any of the above if I've misrepresented anything

**Comment by flukeout** [comment]
@mmmavis Here is one idea at making this doc as a template from one simple HTML document...

http://flukeout.github.io/master-template/template-types/resources.html

You can click the code icon in the bottom-right corner to see the original markup, which has some comments about how the final rendered version was created.

**Comment by flukeout** [comment]
Here's tinyMCE live-editing the Resource List template...
- Loaded a custom stylesheet for the editor
- Included the "insert template" plugin and added the boxes there
  - It's the icon right after redo & undo

http://flukeout.github.io/master-template/template-types/editor.html

cc @gvn @mmmavis

**Comment by hannahkane** [comment]
This is now duped by #25, so closing, though the comments will still be useful.
