### ISSUE TITLE
Prototype Candidate: Ed Hub Community Call landing page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/mofo-cms-experiment#16]
In late March, we will be starting a monthly community call. We need a landing page for the series that includes: 
- some explanatory information about the goals of the calls
- information about the upcoming calls: topic + date/time
- during the actual calls themselves, the landing page should serve as the entry point to the event - including a way to hear/see the call (not sure what tech we're using for these yet) and a way to access the event etherpad
  - access to an archive of previous calls

This content will need to be updated frequently by staff.

No design yet.

**Comment by mmmavis** [comment]
For a simple landing page like this I think it will serve as a good guinea pig candidate :stuck_out_tongue_winking_eye: 

It could probably work even **without** custom field type support. Assuming the page will have 4 major sections

#### 1. Some explanatory information about the goals of the calls

Simple text edits using Calypso. We create a WP Page on Calypso and display content of it as a section on the React site.

#### 2. Information about the upcoming calls: topic + date/time

Simple text edits using Calypso. We create a WP Page on Calypso and display content of it as a section on the React site.
Copying content in Calypso's WYSIWYG editor actually copies the underlying HTML code. So as long as the HTML of the first item on that list contains the HTML info we need to map on the React site side(e.g,. `class`, element type), adding a new item to that list is simply a copy-and-replace task in the WYSIWYG editor. This way we can ensure proper formatting without the support of custom field type. It might be a little hacky, but this sounds like a reasonable workaround for simple landing page like this.

#### 3. Embedded Etherpad

The React site deals with this. Nothing to do in Calypso.

#### 4. An archive of previous calls

Simple text edits using Calypso. We create a WP Page on Calypso and display content of it as a section on the React site. (Similar workflow to Section 2)

Curious about what @simonwex and @gvn think :bowtie:

**Comment by hannahkane** [comment]
Possible to embed the livestream while the calls are actually happening?

**Comment by hannahkane** [comment]
this is now duped by the more generic ticket #17
