### ISSUE TITLE
Content Type: recurring event

### ISSUE THREAD

**Issue by hannahkane** [mozilla/mofo-cms-experiment#17]
**Generic content:**
- page title
- small amount of explanatory text
- list of upcoming scheduled event dates/times
- during event itself—live feed of video stream + embedded etherpad
- archive of previously held events + links to etherpads/videos

**Example use case 1: Curriculum Workshop series landing page**

Beginning on March 8, we're going to start co-hosting a monthly Curriculum Development Workshop for the community. 

The series needs a landing page that will include:
- some explanatory information about the goals of the series 
- information about the upcoming workshops: topic + date/time
- during the actual workshops themselves, the landing page should serve as the entry point to the event - including a way to view the workshop (likely a Google Hangout on Air) and a way to access the event etherpad
- access to an archive of previous workshops

**Example use case #2: Education Hub Community Call**

In late March, we will be starting a monthly community call. We need a landing page for the series that includes: 
- some explanatory information about the goals of the calls
- information about the upcoming calls: topic + date/time
- during the actual calls themselves, the landing page should serve as the entry point to the event - including a way to hear/see the call (not sure what tech we're using for these yet) and a way to access the event etherpad
  - access to an archive of previous calls

**Comment by hannahkane** [comment]
@flukeout @vazquez @cassiemc - this one is a good use case for us to test out.

**Comment by hannahkane** [comment]
Perhaps this should be renamed "recurring event with livestream" since a key component is the embedded livestream?

**Comment by mmmavis** [comment]
:exclamation: This ticket is now locked. Please continue the discussion on https://github.com/mozilla/wp-calypso instead. For more info see [README](https://github.com/mozilla/mofo-cms-experiment).

**Comment by vazquez** [comment]
Tiles Issue: https://github.com/mozilla/mofo-cms-experiment/issues/23 

Tile:  ![screenshot 2016-02-25 13 54 41](https://cloud.githubusercontent.com/assets/1119821/13330558/58ed3d2e-dbc7-11e5-9715-6d382ce7fd42.png)

**Comment by flukeout** [comment]
@vazquez and I co-designed the page, here it is...

![workshop-landing-page](https://cloud.githubusercontent.com/assets/25212/13331774/ef9ed69c-dbb3-11e5-8408-268a4318a515.png)

@hannahkane @chadsansing What do you think? Does it cover the bases? Let me know when you have updated copy and content for this page and we'll update the design to make sure it accommodates everything.

Once we're happy we'll move it to the dev phase, where I can help the dev with some of the unique styling.

@kristinashu - you did some work on the hero images on the teach site, do you have any photos handy that could be a good fit for this page?

**Comment by hannahkane** [comment]
Nice work!

Question: How do you imagine the Past Workshops section works once there are several?

@chadsansing - do you want to write final copy? I can take a shot at it if you don't have time, but probably better coming from you. :)

**Comment by hannahkane** [comment]
Oh - also - is it possible to embed the actual etherpad or no?

**Comment by flukeout** [comment]
@hannahkane For past workshops, I think we'd use a similar design change out the heading above the embedded google hangout.

I'm not sure about embedding an etherpad, it seems like a bad idea that could potentially lead to pressing keys and navigating away from the page by accident. I guess we could try an iframe, although I've never experimented with it.

**Comment by vazquez** [comment]
Once there are several past workshops we could also introduce a "See More..." link that reveals the rest of the links. Just an idea.

**Comment by flukeout** [comment]
Oh yeah good call ricardo, failed to consider that. We can either expand the list if someone clicks "See More.." or navigate to a simple Archive page that will just have a super long list.

I'll update the design to include this and also the styling for viewing a past / archived workshop.

**Comment by kristinashu** [comment]
@flukeout here's the photoshop file where I cropped and tested out some images https://drive.google.com/open?id=0B2irLVDJivhLNndMY1B1d29ZT1E 
There are a few unused image that might work?

**Comment by flukeout** [comment]
Thanks!!

**Comment by hannahkane** [comment]
@chadsansing - would love your feedback on the points @flukeout raised above re: etherpad potentially causing usability issues.

**Comment by chadsansing** [comment]
Sorry to be late; just back from travels.

Design looks swell - I dig the color scheme immensely.

The embedded pad is important to me - I would rather novice users and first-time viewers be able to land and participate here than have multiple tabs or windows open.

I can deliver copy by midweek - the 1st or 2nd at the latest.

Thankful, appreciative, and enthused!

**Comment by cassiemc** [comment]
I totally don't know the answer but might there be any security issues with the embedded etherpad @simonwex? I think the usability is a trade-off, and if it's not technically difficult it's worth seeing if it works fine for @chadsansing's use case. Nice work on the quick co-design @vazquez and @flukeout.

**Comment by flukeout** [comment]
Here's an update with an embedded Etherpad. I also moved the workshop description above the Google hangouts window to keep that closer to the Etherpad. @vazquez Thoughts?

![upcoming-workshop-2](https://cloud.githubusercontent.com/assets/25212/13368138/b7e9a134-dc9c-11e5-86b4-fd4fd1ab609c.png)

**Comment by flukeout** [comment]
We could also change the treatment of the Callout Box for past/archived workshops.

![image](https://cloud.githubusercontent.com/assets/25212/13368186/224af41a-dc9d-11e5-8742-e0c97e6795cc.png)

**Comment by chadsansing** [comment]
Plusses!

**Comment by jgmac1106** [comment]
This is awesome. I

The Calypso CMS  is going to be such an asset and once launched.  Maybe the
 design team might have some extra time to be unchained and let out of the
basement.

I figure they must be imprisoned in a sweat shop to keep cranking out all
these cool things. Be nice to let them out occasionally. I suggest
Wednesday for an hour or two. We don't want to get their hopes too high.

**Comment by vazquez** [comment]
Awesome @flukeout, and I love the "Open in new tab" option.

**Comment by chadsansing** [comment]
Copy shared to @flukeout w/ invitation to provide feedback shipped to @amirad, @ldecoursy, @kgorr, and @poh.

**Comment by flukeout** [comment]
Thanks @chadsansing - I'll incorporate it into the mockup so we can see it in context.

**Comment by flukeout** [comment]
Updated with latest content, just need to figure out the hero image int he top now and we can start implementing.

![upcoming-workshop-w-content](https://cloud.githubusercontent.com/assets/25212/13447296/4713f60e-dfcf-11e5-8e73-214589e6648e.png)

**Comment by chadsansing** [comment]
Looks sweet. Let's delete the second, repetitive paragraph at the top - must have left that in the content doc as an artifact of something else.

Is there a URL for the page or the etherpad yet? Curious about how we will update the pad for each episode.

**Comment by ldecoursy** [comment]
Actually, can we lose the 1st paragraph and keep the 2nd - it has tighter language. Thanks!

**Comment by chadsansing** [comment]
+1 to what @ldecoursy says, @flukeout.

**Comment by flukeout** [comment]
Of course!

**Comment by flukeout** [comment]
Closing this issue as the page is designed and being pushed to prod as we speak. Let's file new issues for changes and requests!
