### ISSUE TITLE
Content Type: initiative landing page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/mofo-cms-experiment#20]
Description: Landing page for an event, program, or campaign.

Generic content:
- image
- title 
- tag line
- date or date range
- intro text
- "Ways to Get Involved" - could be, for example, three boxes with an image, brief text, and a link 

Example Use Case:

We are participating in a program called Letters to the Next President. (See [background info](https://docs.google.com/document/d/1cz459xHMEkax4vHryp3uSFE31xJ-yhkX8UP1etvgC78/edit#heading=h.6wn5diu2jemw).)

By the Fall, we'll need to launch a landing page with background information about the program, at least three learning activities, and logos from partner orgs. 

Additional stuff the team would like: Throughout the fall campaign, we'll want to regularly update the page with additional activities, upcoming events, and a gallery of great letters. (Does this seem like a different content type than Landing page?)

**Comment by ldecoursy** [comment]
Just a note that timing for the landing page would be earlier than the fall–ideally in March or April if possible. The gallery portion could be added in August.

**Comment by hannahkane** [comment]
@cassiemc @vazquez @flukeout - just updated this ticket title and first comment. Please edit as you see fit, and then I'll use this as a model for updating the other tickets.

**Comment by cassiemc** [comment]
This sounds great @hannahkane. For clarity I might call this the 'Event Landing Page' unless you think it's more widely applicable. Strikes me that something that is event-specific might have different requirements than another generic type of landing page.

**Comment by hannahkane** [comment]
Thanks, @cassiemc. Agreed it could use a descriptor—is "event" right for the use case? It's more like a campaign or program, but those have other connotations too. I'll use event for now, but I can imagine some more nuance surfacing as we address more use cases.

**Comment by hannahkane** [comment]
@cassiemc - oh, also, this is different from the "recurring event" described in #17. Maybe that was confusing.

**Comment by cassiemc** [comment]
@hannahkane Ah, I think I did confuse this. How about Initiative Landing Page? Or Program Landing Page? @kristinashu might have thoughts on language here too.

**Comment by hannahkane** [comment]
I like initiative—that suggests the less-than-permanent nature of the use case. Will switch to that unless @kristinashu has further ideas!

**Comment by kristinashu** [comment]
Initiatives sounds good to me.

**Comment by mmmavis** [comment]
:exclamation: This ticket is now locked. Please continue the discussion on https://github.com/mozilla/wp-calypso instead. For more info see [README](https://github.com/mozilla/mofo-cms-experiment).
