### ISSUE TITLE
Content Type: Learning Resources

### ISSUE THREAD

**Issue by hannahkane** [mozilla/mofo-cms-experiment#21]
We have a few different flavors of learning resources that we create regularly:
- lesson plans (for example: http://flukeout.github.io/master-template/teach/#overview)
- activities (for example: http://flukeout.github.io/master-template/science/)
- guides (for example: http://flukeout.github.io/master-template/clubs/)

Though there are different flavors, within each content type there is some consistency about the type of information included, as well as the navigation and structure.

We're currently resolving some of the obstacles to creation by putting together templates that staff can use to create new materials. But a proper CMS might solve for additional requirements such as improved translation workflows and collaborative editing.

**Comment by mmmavis** [comment]
:exclamation: This ticket is now locked. Please continue the discussion on https://github.com/mozilla/wp-calypso instead. For more info see [README](https://github.com/mozilla/mofo-cms-experiment).
