### ISSUE TITLE
Content Types: UI Tiles

### ISSUE THREAD

**Issue by vazquez** [mozilla/mofo-cms-experiment#23]
I made this to:
- Show the different types of content types in a visual way (not a final list)
- Discuss the principles of what would be a good Calypso candidate

![calypso](https://cloud.githubusercontent.com/assets/1119821/13157653/18697f80-d657-11e5-83d6-8b79e8151a74.png)

cc @hannahkane @gvn @mmmavis @flukeout @cassiemc @simonwex

**Comment by hannahkane** [comment]
LOVE THIS, @vazquez. Rules of Engagement and the Tiles so far are terrific.

For a broader audience, we might want to clarify what "bespoke design elements" are—people may not realize that they can customize things like color (within a defined palette) and images, or change the number of items in the navigation or a list. 

I'm not actually sure about the limits of the templates myself - for example, in Event Landing Page 2, does the author have to use all three columns? (I think the answer is yes, and if we want to have variations with, say, 2 or 4 columns, those would be different templates. Is that right? These are the kinds of questions/requests I'm anticipating from staff.)

**Comment by cassiemc** [comment]
Yes, this is awesome progress @vazquez! In addition to more points about what each template type entails, it might also be interesting to lay out what interactions and use cases they support. Ie. which pages (or page flows) best support a multi-page experience, are they all equal in terms of signing in, onboarding, etc. I think I might also tweak language and tone on 'rules of engagement' but no need to spin wheels on that at this point. I think the use case that is missing though is the element of speed, when someone needs to spin up a site quickly with little to no available resources. Once we have actual templates it'll be super interesting to test our assumptions on how people will want to engage with this. Nice work!

**Comment by vazquez** [comment]
Here we go with a second iteration! I addressed feedback on:
- The content that each template type entails
- Speed!

I have to think about ways to show:
- Limits of the templates
- Supported interactions and use-cases each template supports

We can tweak anything. Let me know if you think my speed estimates were a bit off, etc.

![calypso-2](https://cloud.githubusercontent.com/assets/1119821/13180893/77a32c2a-d6f8-11e5-9553-8bcd8e2c1037.png)

**Comment by cassiemc** [comment]
B/c this is rather text heavy, @vazquez can you through this written content into a google doc? Would love some collaborative editing there w/o working through the design at the same time. Looking really good!

**Comment by hannahkane** [comment]
+1 to editing in a google doc. I have some minor edits to suggest.

**Comment by vazquez** [comment]
Here is a Google Doc with all the content: https://docs.google.com/a/mozilla.com/document/d/1VYsorOj75we-kV-a0h8tTV7DwvPRr7NksiiBCM77iyI/edit?usp=sharing

**Comment by cassiemc** [comment]
Thanks @vazquez!

**Comment by hannahkane** [comment]
Added some comments to the google doc. I am really loving this guide and these tiles.

**Comment by cassiemc** [comment]
I also left some comments. @vazquez would you be okay if @hannahkane and I hashed out a new version of the words together, so you can focus on design? If so, perhaps we can finalize this doc Monday @hannahkane?

**Comment by hannahkane** [comment]
wfm, @cassiemc.

**Comment by vazquez** [comment]
Works for me too :)

**Comment by cassiemc** [comment]
@vazquez - Met with @hannahkane today and updated the content doc. Simplified a lot of the copy, including the names of each template and the items listed next to each (which is sort of redundant b/c of the graphics you created). It's not totally finalized but thinking this should also be laid out more like a grid, so it's easier to explore. 

<img width="1355" alt="screen shot 2016-02-22 at 3 21 15 pm" src="https://cloud.githubusercontent.com/assets/1186326/13231448/f19af608-d977-11e5-9f49-860dd0ebd600.png">

Here's the updated doc so far. We are going to keep working on this tomorrow. https://docs.google.com/document/d/1VYsorOj75we-kV-a0h8tTV7DwvPRr7NksiiBCM77iyI/edit#

**Comment by vazquez** [comment]
I know the text is still up in the air, but here in an update:

![calypso-3](https://cloud.githubusercontent.com/assets/1119821/13256726/df05de98-da19-11e5-9b01-9199ee7ee590.png)

**Comment by cassiemc** [comment]
We were intending to leave out the technical requirements from this view. I also think the thumbs should be bigger for scannability, and would prefer more thumbnails in a row – could the descriptions go below the thumbs to accommodate this? I also think the informational text could be on a separate page (perhaps referenced in book.mozillafoundation.org) with a link at the top of this.

**Comment by vazquez** [comment]
I have updated https://book.mozillafoundation.org/calypso.html with content from the Google Doc. I have to make it a little bit prettier, as using a table is not working so well right now. I'm also going to add a WIP notice at the top.

**Comment by mmmavis** [comment]
:exclamation: This ticket is now locked. Please continue the discussion on https://github.com/mozilla/wp-calypso instead. For more info see [README](https://github.com/mozilla/mofo-cms-experiment).
