### ISSUE TITLE
Create WP site & find home for code for "Curriculum Workshop series landing page"

### ISSUE THREAD

**Issue by simonwex** [mozilla/mofo-cms-experiment#24]
We'll need to figure out a few things, like: 
- [ ] What domain this public-facing site lives on
- [ ] Is there an existing repo that we should be checking our code into?
- [ ] What to call the "public-facing" site
- [ ] Who needs access to calypso

This is a single instance of #17

**Comment by mmmavis** [comment]
@hannahkane is there a deadline for this site to be live?

**Comment by ldecoursy** [comment]
The first call is March 8th, would be great to have in advance for promotion purposes, but we can find a backup (direct link to YouTube streaming) if that timing isn't possible.

**Comment by mmmavis** [comment]
:exclamation: This ticket is now locked. Please continue the discussion on https://github.com/mozilla/wp-calypso instead. For more info see [README](https://github.com/mozilla/mofo-cms-experiment).
