### ISSUE TITLE
Content Type: List

### ISSUE THREAD

**Issue by hannahkane** [mozilla/mofo-cms-experiment#25]
**Generic content:**
- Intro content
- Section headings (maybe a few levels?)
- List items / links

**Example use case #1:**

The Clubs Resources landing page—work started in #15 

**Example use case #2:**

Science Study Group lessons (they are currently accessed from [github](https://github.com/mozillascience/studyGroupLessons) - not sure yet if moving the landing page to a CMS would be desirable

**Comment by mmmavis** [comment]
:exclamation: This ticket is now locked. Please continue the discussion on https://github.com/mozilla/wp-calypso instead. For more info see [README](https://github.com/mozilla/mofo-cms-experiment).

**Comment by amirad** [comment]
@hannahkane not sure where's the best ticket to share this but been working on organizing our guides/resources for this project here: https://docs.google.com/spreadsheets/d/1dpU02AiN2otBuN0W4Xt9cbIDMpBd3jKKLPs_1QsxeQo/edit#gid=0

**Comment by hannahkane** [comment]
Thanks, @amirad! It looks like this would still fit well into the layout that's been designed. Flagging @vazquez to confirm that the design for the List template can accommodate several layers of sub-headings. I can imagine, for example, wanting an h2 for each of the major headings (corresponding to the tab titles on Amira's spreadsheet) and then perhaps using h3's to further divide up the Guides into sub-sections, since there are so many.

Also, @vazquez - I don't think in this particular use case (correct me if I'm wrong, @amirad) we have images associated with the resources, but I wonder if the generic version of the List template should include thumbnails as an option. Is that possible?

**Comment by vazquez** [comment]
This is the layout we have so far. It is doable to separate these links into groups with their own headings. 

![screen shot 2016-03-02 at 16 51 45](https://cloud.githubusercontent.com/assets/1119821/13476710/1adecd02-e097-11e5-893b-a8f387b8b6e6.png)

**Comment by vazquez** [comment]
@hannahkane –Would it be okay if we steered away from thumbnail images in this layout? I want to keep this as simple as possible for now while we investigate the powers of Calypso and TinyMCE.

**Comment by hannahkane** [comment]
Yes. I'll make it a requirement for a layout in an upcoming milestone, so we don't forget!

**Comment by vazquez** [comment]
:+1:

**Comment by amirad** [comment]
Yes to subheadings, that's great. One of the tabs on the spreadsheet is for documents/resources (non guide like things) so that can just be it's own subheading. 

I'm always about the simple is better so if we never have thumbnail images I'm okay with that
