### ISSUE TITLE
Create a repo for our version of Calypso

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mofo-cms-experiment#31]
I think we should probably just repurpose this one since each of "public facing" React sites will have to live on individual repos anyway.

/cc @simonwex @gvn @Pomax @vazquez @flukeout

**Comment by gvn** [comment]
I was just wondering where that lived. :+1: 

Is this repo's current code still being worked on? Have we proved what we needed to with it? If not, maybe it could be moved to another branch and `master` could be for our Calypso fork?

**Comment by mmmavis** [comment]
The code that's currently on this repo is more like my experiment of consuming WP API data on a React site. We are gonna be using @Pomax 's [ReactRoutedExample](https://github.com/Pomax/ReactRoutedExample) as the base of our public-facing sites so I think there's no need to preserve my code (I have a fork under my account anyway).

**Comment by gvn** [comment]
Ok cool. Can you let us all know when this repo becomes a Calypso fork?

**Comment by mmmavis** [comment]
Yea, I'm trying to figure out how I can make this existing repo appeared as <img width="184" alt="forked from [Automattic/wp-calypso](https://github.com/Automattic/wp-calypso" src="https://cloud.githubusercontent.com/assets/2896608/13266838/cdef6b78-da2e-11e5-9883-b809cb54ea2c.png"> :grimacing: Any tips?

**Comment by gvn** [comment]
Not sure. Maybe we should just start a new repo/fork? @simonwex thoughts?

**Comment by Pomax** [comment]
I'd suggest creating a new repo by forking calypso, and then migrate the issues.

**Comment by mmmavis** [comment]
Fork is here: https://github.com/mozilla/wp-calypso. 

Let's just manually copy the issues over so we can retire this `mofo-cms-experiment` repo?

**Comment by gvn** [comment]
:+1:

**Comment by mmmavis** [comment]
Regarding migrating issues over to https://github.com/mozilla/wp-calypso ...

Just realized I have 2-way auth enabled on my Github account, which means Atul's awesome [migration script](https://github.com/toolness/learning-issue-migrator) won't work for me as is. I rather be focusing on understanding Calypso than getting migration script to work at this stage. Can someone who doesn't have 2-way auth enabled run this script instead? Else we can each take 5 issues and manually copy them over I guess... :eyes: :speak_no_evil: 

/cc @simonwex @gvn @Pomax

**Comment by mmmavis** [comment]
Ticket for next steps filed: https://github.com/mozilla/mofo-cms-experiment/issues/33. Let's close this ticket.
