### ISSUE TITLE
Use Case: Maker Party

### ISSUE THREAD

**Issue by hannahkane** [mozilla/mofo-cms-experiment#32]
Maker Party content is a good use case for us, because it requires us to explore:
- a multi-page experience
- a page with a form
- it also allows us to test our layouts so far

Use case requirements (I don't know what the MP site requirements will actually be this year, this is just a guess for our purposes):
- a homepage with a hero image, a Sign Up form (user submits email address), some text, a collection of three case studies (each has small photo + some text), an embedded video, and a link to the resources page
- a resources page with a list of resources/activities, with thumbnail images next to each

Look at https://teach.mozilla.org/events as reference, but we should see if we can display comparable information within the constraints of our existing layout templates.

**Comment by hannahkane** [comment]
cc @simonwex @gvn @mmmavis @Pomax @vazquez @flukeout

**Comment by mmmavis** [comment]
:exclamation: This ticket is now locked. Please continue the discussion on https://github.com/mozilla/wp-calypso instead. For more info see [README](https://github.com/mozilla/mofo-cms-experiment).
